config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  post 'signin', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  root 'topics#index'
  
  resources :users, only: [:create]
  
  scope path: '~:username', module: 'users', as: 'user' do
    root to: 'topics#index'
  end
 

end

app/models/user.rb
class User < ActiveRecord::Base
  
  include Gravtastic
  gravtastic secure: true, default: 'wavatar', rating: 'G', size: 48
  mount_uploader :avatar, AvatarUploader
  
  has_secure_password
  
  validates :username, uniqueness: {case_sensitive: false}, presence: true, format: { with: /\A[a-z0-9][a-z0-9-]*\z/i }
  validates :name, presence: true
  validates :email, uniqueness: {case_sensitive: false}, presence: true, format: { with: /\A([^@\s]+)@((?:[a-z0-9-]+\.)+[a-z]{2,})\z/i }
  
  def remember_token
    [id, Digest::SHA512.hexdigest(password_digest)].join('$')
  end

  def self.find_by_remember_tokena(token)
    user = find_by_id(token.split('$').first)
    (user && Rack::Utils.secure_compare(user.remember_token, token)) ? user : nil
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :signed_in?, :current_user
  
  def signed_in?
    !!current_user
  end
  
  def store_location(path)
    session[:return_to] = path
  end
  
  def redirect_back_or_default(default)
    redirect_to(session.delete(:return_to) || default)
  end
  
  def login_as(user)
    session[:user_id] = user.id
    @current_user = user 
  end
 
  def current_user
    @current_user ||= login_from_session || login_from_cookies unless defined?(@current_user)
    @current_user
  end
  
  def login_from_session
    if session[:user_id].present?
      begin
        User.find session[:user_id]
      rescue
        session[:user_id] = nil
      end
    end
  end
  
  def login_from_cookies
    if cookies[:remember_token].present?
      if user = User.find_by_remember_token(cookies[:remember_token])
        session[:user_id] = user.id
        user
      else 
        forget_me
        nil
      end
    end
  end
  
  def remember_me
    cookies[:remember_token] = {
      value: current_user.remember_token,
      expires: 2.weeks.from_now,
      httponly: true
    }
  end
  
  def forget_me
    cookies.delete(:remember_token)
  end
  
  def logout
    session.delete(:user_id)
    @current_user = nil 
    forget_me
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    store_location params[:return_to]
  end
  
  def create
    # Get the login name from parameters
    login = login_params[:login]
    # Query the user from database based on the login name is e-mail or username
    @user = if login.include?('@')
              User.where('lower(email) = lower(?)', login).first
            else
              User.where('lower(username) = lower(?)', login).first
            end 
    if @user && @user.authenticate(login_params[:password])
      login_as @user
      remember_me
      redirect_back_or_default root_url
    else
      flash.now[:warning] = 'Incorrect user name or password'
      render 'new'
    end
  end
  
  def destroy 
    logout
    redirect_to root_url 
  end
  
  private 

  def login_params
    params.require(:user).permit(:login, :password)
  end
end

app/controllers/settings/profiles_controller.rb
class Settings::ProfilesController < ApplicationController
  def show
  end

  def update
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index 
  end 
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  before_action :find_user

  private 

  def find_user
    @user = User.where('lower(username) = ?', params[:username].downcase).first!
  end
end

app/controllers/users/topics_controller.rb
class Users::TopicsController < Users::ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    store_location params[:return_to]
    @user = User.new
  end
  
  def create
    @user = User.new params.require(:user).permit(:username, :email, :name, :password)
    if @user.save 
      # login_as @user
      puts 'SAVE USER SUCCESSFULLY'
      redirect_back_or_default root_url
    else
      render :new
    end
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def return_to_path(path)
    case path
    when '/', /^\/login/, /^\/signup/
      nil
    else
      path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">Tiny Forum on Rails</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li class="dropdown">
            <!-- User's avatar image -->
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= image_tag current_user.gravatar_url, class: 'img-circle img-avatar' %>
              <%= current_user.name %>
              <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
              <a href="<%= user_root_path(username: current_user.username) %>">Profile</a>
              </li>
              <li class="divider"></li>
              <li class="dropdown-header">Likes</li>
              <li>
                <a href="#">Topics</a>
              </li>
              <li>
                <a href="#">Comments</a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="#">Settings</a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="<%= logout_path %>" data-method="delete">Logout</a>
              </li>
            </ul>
          </li>
          
        <% else %>
          <li><a href='<%= signup_path(:return_to => params[:return_to] || return_to_path(request.fullpath)) %>'>Sign up</a></li>
          <li><a href='<%= signin_path(retrun_to: params[:retrun_to] || return_to_path(request.fullpath)) %>'>Sign in</a></li>
        <% end %>
      </ul>

      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="#">Community</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <%= yield %>

</body>
</html>

app/views/settings/profiles/show.html.erb
<%= content_for(:page_title, "Profile") %>
<h3>Profile Settings Show</h3>

app/views/settings/profiles/update.html.erb
<h1>Settings::Profiles#update</h1>
<p>Find me in app/views/settings/profiles/update.html.erb</p>

app/views/users/_profile.html.erb
<div class="panel user-profile">
  <div class="panel-body">
    <div class="user-profile-avatar">
      <%= image_tag user.gravatar_url(size: 96), class: 'img-rounded' %>
    </div>

    <div class="user-profile-name">
      <%= user.name %>
      <span class="text-muted"><%= "@#{user.username}" %></span>
    </div>

    <div class="user-profile-bio">
      <%= simple_format user.bio %>
    </div>

    <% if signed_in? && user == current_user %>
      <div class="panel-footer clearfix">
        <div class="pull-right">
          <a class="btn btn-default" href="#">Edit Profile</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel">
          <div class="panel-heading">
            <h3 class="panel-title">Sign up</h3>
          </div>
          <div class="panel-body">
            <%= form_for(@user, html: {id: 'new-user-form'}) do |f| %>
              <div class="form-group">
                <%= f.label :name, class: 'control-label' %>
                <%= f.text_field :name, placeholder: 'your fullname', tabindex: 1, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :email, class: 'control-label' %>
                <%= f.text_field :email, placeholder: 'your email', tabindex: 2, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :username, class: 'control-label' %>
                <%= f.text_field :username, placeholder: 'pick a user name', tabindex: 3, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password, class: 'control-label' %>
                <%= f.password_field :password, placeholder: 'choose a password', tabindex: 4, class: 'form-control' %>
              </div>
              <%= f.submit 'create account', class: 'btn btn-success', tabindex: 5 %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/topics/index.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/profile', user: @user%>
      </div>
    </div>
  </div>
</div>